version: "3.8"

services:
  veranito-web:
    build: ./veranito-web
    expose:
      - "3000"

  veranito-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: garchados123
      POSTGRES_DB: veranito
    volumes:
      - veranito-pgdata:/var/lib/postgresql/data

volumes:
  veranito-pgdata:
