version: "3.8"

services:
  veranito-web:
    build: ./veranito-web
    expose:
      - "3000"

  veranito-backend:
    build: ./backend
    expose:
      - "3001"
    environment:
      - PORT=3001
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=veranito-postgres
      - POSTGRES_PORT=5432
    depends_on:
      - veranito-postgres

  veranito-postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - veranito-pgdata:/var/lib/postgresql/data

volumes:
  veranito-pgdata:

networks:
  default:
    external: true
    name: proxy_net
